### ISSUE TITLE
MinIO connection in local testing

### ISSUE THREAD

**Issue by steinsgateted** [grycap/oscar#156]
### Steps to Reproduce the Problem
Hello team,
I'm currently trying to run OSCAR locally.
I would like some clarifications about the connection of minio on localhost.
1. I followed the [doc](https://docs.oscar.grycap.net/local-testing/) to execute: `curl -sSL http://go.oscar.grycap.net | bash`
1. Then I create a bucket, there will be an error:
```
request.js:150
PUT https://minio.minio:9000/abc
net::ERR_NAME_NOT_RESOLVED
```
Thank you.
### Specifications

- Platform: Ubuntu 20.04 Chrome

### Screenshots
![2022-07-18 23-53-58 的螢幕擷圖](https://user-images.githubusercontent.com/71066027/179558146-7b652d98-875c-4bd7-ab94-83598339159c.png)

### Possible Solution

Any thoughts as to potential solutions or ideas to go about finding one. Please include links to any research.

**Comment by srisco** [comment]
Hi @steinsgateted, thanks for reporting the issue. This problem is documented in another section of the same [docs](https://docs.oscar.grycap.net/local-testing/#deploy-oscar) page:

> *Note that the OSCAR server has been configured to use the ClusterIP service of MinIO for internal communication. This blocks the MinIO section in the OSCAR web interface, so to download and upload files you must connect directly to MinIO (`http://localhost:30300`).*

However, we've patched it recently and the issue will be solved in the next OSCAR release, I hope to update the helm chart later this week. I let this issue open to notify you when the release is ready in order to ensure it's solved.

Cheers.

**Comment by srisco** [comment]
Hello @steinsgateted, I've just updated the helm chart, if you delete the old kind cluster (`kind delete cluster --name=oscar-test`) and deploy a new one the issue must be solved.

Let me know if you have any other problem.

Regards.

**Comment by steinsgateted** [comment]
Hi @srisco,
Thank you for the explanation.
I can create bucket and run the ImageMagick example.
Thank you. If I have other problems I will open new issues.

Regards.
