### ISSUE TITLE
The pod name of each function is random

### ISSUE THREAD

**Issue by steinsgateted** [grycap/oscar#158]
### Describe the solution you'd like
Use `kubectl get pod -n=oscar-svc`, the pod name of each function is random.
If the pod name contains the service name, we can know which pod belongs to which function through kubectl.

**Comment by srisco** [comment]
Hi @steinsgateted, this is set by design, as Kubernetes doesn't allow the same name for multiple jobs.

You can get the jobs/pods of a specific OSCAR service via the web interface, with the `oscar-cli` command [`logs list`](https://github.com/grycap/oscar-cli#logs-list) or, if you prefer to use kubectl by filtering by the `oscar_service` label:

```
kubectl get pods -n oscar-svc -l oscar_service=<SERVICE_NAME>
```

**Comment by steinsgateted** [comment]
Hi @srisco,
I see. Thank you for the explanation.
